package com.wh.task.model;

import java.math.BigDecimal;
import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucs_user.id
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucs_user.real_name
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucs_user.phone_no
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    private String phoneNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucs_user.email
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucs_user.type
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucs_user.id_card_type
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    private String idCardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucs_user.id_card_no
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    private String idCardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucs_user.status
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucs_user.reg_source
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    private String regSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucs_user.reg_platform
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    private String regPlatform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucs_user.device
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    private String device;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucs_user.is_stock
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    private String isStock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucs_user.stock_status
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    private String stockStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucs_user.is_open_account
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    private String isOpenAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucs_user.reg_time
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    private Date regTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucs_user.level
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucs_user.growth_num
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    private Long growthNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucs_user.coin_num
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    private Long coinNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucs_user.sex
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucs_user.email_check
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    private String emailCheck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucs_user.open_time
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    private Date openTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucs_user.is_new
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    private String isNew;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucs_user.guarantee_code
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    private String guaranteeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucs_user.invite_code
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    private String inviteCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucs_user.my_invite_code
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    private String myInviteCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucs_user.available_amount
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    private BigDecimal availableAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucs_user.token_valide_time
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    private Integer tokenValideTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucs_user.email_bind_time
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    private Date emailBindTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucs_user.is_pass_risk_rating
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    private String isPassRiskRating;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucs_user.is_offline
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    private String isOffline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucs_user.highest_level
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    private String highestLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucs_user.is_agree
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    private String isAgree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucs_user.agree_time
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    private Date agreeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucs_user.user_type
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    private String userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucs_user.score_mall_grant
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    private String scoreMallGrant;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucs_user.id
     *
     * @return the value of ucs_user.id
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucs_user.id
     *
     * @param id the value for ucs_user.id
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucs_user.real_name
     *
     * @return the value of ucs_user.real_name
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucs_user.real_name
     *
     * @param realName the value for ucs_user.real_name
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucs_user.phone_no
     *
     * @return the value of ucs_user.phone_no
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucs_user.phone_no
     *
     * @param phoneNo the value for ucs_user.phone_no
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo == null ? null : phoneNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucs_user.email
     *
     * @return the value of ucs_user.email
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucs_user.email
     *
     * @param email the value for ucs_user.email
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucs_user.type
     *
     * @return the value of ucs_user.type
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucs_user.type
     *
     * @param type the value for ucs_user.type
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucs_user.id_card_type
     *
     * @return the value of ucs_user.id_card_type
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public String getIdCardType() {
        return idCardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucs_user.id_card_type
     *
     * @param idCardType the value for ucs_user.id_card_type
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public void setIdCardType(String idCardType) {
        this.idCardType = idCardType == null ? null : idCardType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucs_user.id_card_no
     *
     * @return the value of ucs_user.id_card_no
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public String getIdCardNo() {
        return idCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucs_user.id_card_no
     *
     * @param idCardNo the value for ucs_user.id_card_no
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public void setIdCardNo(String idCardNo) {
        this.idCardNo = idCardNo == null ? null : idCardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucs_user.status
     *
     * @return the value of ucs_user.status
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucs_user.status
     *
     * @param status the value for ucs_user.status
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucs_user.reg_source
     *
     * @return the value of ucs_user.reg_source
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public String getRegSource() {
        return regSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucs_user.reg_source
     *
     * @param regSource the value for ucs_user.reg_source
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public void setRegSource(String regSource) {
        this.regSource = regSource == null ? null : regSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucs_user.reg_platform
     *
     * @return the value of ucs_user.reg_platform
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public String getRegPlatform() {
        return regPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucs_user.reg_platform
     *
     * @param regPlatform the value for ucs_user.reg_platform
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public void setRegPlatform(String regPlatform) {
        this.regPlatform = regPlatform == null ? null : regPlatform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucs_user.device
     *
     * @return the value of ucs_user.device
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public String getDevice() {
        return device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucs_user.device
     *
     * @param device the value for ucs_user.device
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public void setDevice(String device) {
        this.device = device == null ? null : device.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucs_user.is_stock
     *
     * @return the value of ucs_user.is_stock
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public String getIsStock() {
        return isStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucs_user.is_stock
     *
     * @param isStock the value for ucs_user.is_stock
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public void setIsStock(String isStock) {
        this.isStock = isStock == null ? null : isStock.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucs_user.stock_status
     *
     * @return the value of ucs_user.stock_status
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public String getStockStatus() {
        return stockStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucs_user.stock_status
     *
     * @param stockStatus the value for ucs_user.stock_status
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public void setStockStatus(String stockStatus) {
        this.stockStatus = stockStatus == null ? null : stockStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucs_user.is_open_account
     *
     * @return the value of ucs_user.is_open_account
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public String getIsOpenAccount() {
        return isOpenAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucs_user.is_open_account
     *
     * @param isOpenAccount the value for ucs_user.is_open_account
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public void setIsOpenAccount(String isOpenAccount) {
        this.isOpenAccount = isOpenAccount == null ? null : isOpenAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucs_user.reg_time
     *
     * @return the value of ucs_user.reg_time
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public Date getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucs_user.reg_time
     *
     * @param regTime the value for ucs_user.reg_time
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucs_user.level
     *
     * @return the value of ucs_user.level
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucs_user.level
     *
     * @param level the value for ucs_user.level
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucs_user.growth_num
     *
     * @return the value of ucs_user.growth_num
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public Long getGrowthNum() {
        return growthNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucs_user.growth_num
     *
     * @param growthNum the value for ucs_user.growth_num
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public void setGrowthNum(Long growthNum) {
        this.growthNum = growthNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucs_user.coin_num
     *
     * @return the value of ucs_user.coin_num
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public Long getCoinNum() {
        return coinNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucs_user.coin_num
     *
     * @param coinNum the value for ucs_user.coin_num
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public void setCoinNum(Long coinNum) {
        this.coinNum = coinNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucs_user.sex
     *
     * @return the value of ucs_user.sex
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucs_user.sex
     *
     * @param sex the value for ucs_user.sex
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucs_user.email_check
     *
     * @return the value of ucs_user.email_check
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public String getEmailCheck() {
        return emailCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucs_user.email_check
     *
     * @param emailCheck the value for ucs_user.email_check
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public void setEmailCheck(String emailCheck) {
        this.emailCheck = emailCheck == null ? null : emailCheck.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucs_user.open_time
     *
     * @return the value of ucs_user.open_time
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public Date getOpenTime() {
        return openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucs_user.open_time
     *
     * @param openTime the value for ucs_user.open_time
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public void setOpenTime(Date openTime) {
        this.openTime = openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucs_user.is_new
     *
     * @return the value of ucs_user.is_new
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public String getIsNew() {
        return isNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucs_user.is_new
     *
     * @param isNew the value for ucs_user.is_new
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public void setIsNew(String isNew) {
        this.isNew = isNew == null ? null : isNew.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucs_user.guarantee_code
     *
     * @return the value of ucs_user.guarantee_code
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public String getGuaranteeCode() {
        return guaranteeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucs_user.guarantee_code
     *
     * @param guaranteeCode the value for ucs_user.guarantee_code
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public void setGuaranteeCode(String guaranteeCode) {
        this.guaranteeCode = guaranteeCode == null ? null : guaranteeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucs_user.invite_code
     *
     * @return the value of ucs_user.invite_code
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public String getInviteCode() {
        return inviteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucs_user.invite_code
     *
     * @param inviteCode the value for ucs_user.invite_code
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public void setInviteCode(String inviteCode) {
        this.inviteCode = inviteCode == null ? null : inviteCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucs_user.my_invite_code
     *
     * @return the value of ucs_user.my_invite_code
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public String getMyInviteCode() {
        return myInviteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucs_user.my_invite_code
     *
     * @param myInviteCode the value for ucs_user.my_invite_code
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public void setMyInviteCode(String myInviteCode) {
        this.myInviteCode = myInviteCode == null ? null : myInviteCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucs_user.available_amount
     *
     * @return the value of ucs_user.available_amount
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public BigDecimal getAvailableAmount() {
        return availableAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucs_user.available_amount
     *
     * @param availableAmount the value for ucs_user.available_amount
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public void setAvailableAmount(BigDecimal availableAmount) {
        this.availableAmount = availableAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucs_user.token_valide_time
     *
     * @return the value of ucs_user.token_valide_time
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public Integer getTokenValideTime() {
        return tokenValideTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucs_user.token_valide_time
     *
     * @param tokenValideTime the value for ucs_user.token_valide_time
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public void setTokenValideTime(Integer tokenValideTime) {
        this.tokenValideTime = tokenValideTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucs_user.email_bind_time
     *
     * @return the value of ucs_user.email_bind_time
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public Date getEmailBindTime() {
        return emailBindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucs_user.email_bind_time
     *
     * @param emailBindTime the value for ucs_user.email_bind_time
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public void setEmailBindTime(Date emailBindTime) {
        this.emailBindTime = emailBindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucs_user.is_pass_risk_rating
     *
     * @return the value of ucs_user.is_pass_risk_rating
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public String getIsPassRiskRating() {
        return isPassRiskRating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucs_user.is_pass_risk_rating
     *
     * @param isPassRiskRating the value for ucs_user.is_pass_risk_rating
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public void setIsPassRiskRating(String isPassRiskRating) {
        this.isPassRiskRating = isPassRiskRating == null ? null : isPassRiskRating.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucs_user.is_offline
     *
     * @return the value of ucs_user.is_offline
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public String getIsOffline() {
        return isOffline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucs_user.is_offline
     *
     * @param isOffline the value for ucs_user.is_offline
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public void setIsOffline(String isOffline) {
        this.isOffline = isOffline == null ? null : isOffline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucs_user.highest_level
     *
     * @return the value of ucs_user.highest_level
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public String getHighestLevel() {
        return highestLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucs_user.highest_level
     *
     * @param highestLevel the value for ucs_user.highest_level
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public void setHighestLevel(String highestLevel) {
        this.highestLevel = highestLevel == null ? null : highestLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucs_user.is_agree
     *
     * @return the value of ucs_user.is_agree
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public String getIsAgree() {
        return isAgree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucs_user.is_agree
     *
     * @param isAgree the value for ucs_user.is_agree
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public void setIsAgree(String isAgree) {
        this.isAgree = isAgree == null ? null : isAgree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucs_user.agree_time
     *
     * @return the value of ucs_user.agree_time
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public Date getAgreeTime() {
        return agreeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucs_user.agree_time
     *
     * @param agreeTime the value for ucs_user.agree_time
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public void setAgreeTime(Date agreeTime) {
        this.agreeTime = agreeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucs_user.user_type
     *
     * @return the value of ucs_user.user_type
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucs_user.user_type
     *
     * @param userType the value for ucs_user.user_type
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucs_user.score_mall_grant
     *
     * @return the value of ucs_user.score_mall_grant
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public String getScoreMallGrant() {
        return scoreMallGrant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucs_user.score_mall_grant
     *
     * @param scoreMallGrant the value for ucs_user.score_mall_grant
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public void setScoreMallGrant(String scoreMallGrant) {
        this.scoreMallGrant = scoreMallGrant == null ? null : scoreMallGrant.trim();
    }
}