package com.wh.task.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ucs_user
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ucs_user
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ucs_user
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ucs_user
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public UserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ucs_user
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ucs_user
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ucs_user
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ucs_user
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ucs_user
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ucs_user
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ucs_user
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ucs_user
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ucs_user
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ucs_user
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ucs_user
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andRealNameIsNull() {
            addCriterion("real_name is null");
            return (Criteria) this;
        }

        public Criteria andRealNameIsNotNull() {
            addCriterion("real_name is not null");
            return (Criteria) this;
        }

        public Criteria andRealNameEqualTo(String value) {
            addCriterion("real_name =", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotEqualTo(String value) {
            addCriterion("real_name <>", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameGreaterThan(String value) {
            addCriterion("real_name >", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameGreaterThanOrEqualTo(String value) {
            addCriterion("real_name >=", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLessThan(String value) {
            addCriterion("real_name <", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLessThanOrEqualTo(String value) {
            addCriterion("real_name <=", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLike(String value) {
            addCriterion("real_name like", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotLike(String value) {
            addCriterion("real_name not like", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameIn(List<String> values) {
            addCriterion("real_name in", values, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotIn(List<String> values) {
            addCriterion("real_name not in", values, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameBetween(String value1, String value2) {
            addCriterion("real_name between", value1, value2, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotBetween(String value1, String value2) {
            addCriterion("real_name not between", value1, value2, "realName");
            return (Criteria) this;
        }

        public Criteria andPhoneNoIsNull() {
            addCriterion("phone_no is null");
            return (Criteria) this;
        }

        public Criteria andPhoneNoIsNotNull() {
            addCriterion("phone_no is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneNoEqualTo(String value) {
            addCriterion("phone_no =", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoNotEqualTo(String value) {
            addCriterion("phone_no <>", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoGreaterThan(String value) {
            addCriterion("phone_no >", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoGreaterThanOrEqualTo(String value) {
            addCriterion("phone_no >=", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoLessThan(String value) {
            addCriterion("phone_no <", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoLessThanOrEqualTo(String value) {
            addCriterion("phone_no <=", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoLike(String value) {
            addCriterion("phone_no like", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoNotLike(String value) {
            addCriterion("phone_no not like", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoIn(List<String> values) {
            addCriterion("phone_no in", values, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoNotIn(List<String> values) {
            addCriterion("phone_no not in", values, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoBetween(String value1, String value2) {
            addCriterion("phone_no between", value1, value2, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoNotBetween(String value1, String value2) {
            addCriterion("phone_no not between", value1, value2, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andIdCardTypeIsNull() {
            addCriterion("id_card_type is null");
            return (Criteria) this;
        }

        public Criteria andIdCardTypeIsNotNull() {
            addCriterion("id_card_type is not null");
            return (Criteria) this;
        }

        public Criteria andIdCardTypeEqualTo(String value) {
            addCriterion("id_card_type =", value, "idCardType");
            return (Criteria) this;
        }

        public Criteria andIdCardTypeNotEqualTo(String value) {
            addCriterion("id_card_type <>", value, "idCardType");
            return (Criteria) this;
        }

        public Criteria andIdCardTypeGreaterThan(String value) {
            addCriterion("id_card_type >", value, "idCardType");
            return (Criteria) this;
        }

        public Criteria andIdCardTypeGreaterThanOrEqualTo(String value) {
            addCriterion("id_card_type >=", value, "idCardType");
            return (Criteria) this;
        }

        public Criteria andIdCardTypeLessThan(String value) {
            addCriterion("id_card_type <", value, "idCardType");
            return (Criteria) this;
        }

        public Criteria andIdCardTypeLessThanOrEqualTo(String value) {
            addCriterion("id_card_type <=", value, "idCardType");
            return (Criteria) this;
        }

        public Criteria andIdCardTypeLike(String value) {
            addCriterion("id_card_type like", value, "idCardType");
            return (Criteria) this;
        }

        public Criteria andIdCardTypeNotLike(String value) {
            addCriterion("id_card_type not like", value, "idCardType");
            return (Criteria) this;
        }

        public Criteria andIdCardTypeIn(List<String> values) {
            addCriterion("id_card_type in", values, "idCardType");
            return (Criteria) this;
        }

        public Criteria andIdCardTypeNotIn(List<String> values) {
            addCriterion("id_card_type not in", values, "idCardType");
            return (Criteria) this;
        }

        public Criteria andIdCardTypeBetween(String value1, String value2) {
            addCriterion("id_card_type between", value1, value2, "idCardType");
            return (Criteria) this;
        }

        public Criteria andIdCardTypeNotBetween(String value1, String value2) {
            addCriterion("id_card_type not between", value1, value2, "idCardType");
            return (Criteria) this;
        }

        public Criteria andIdCardNoIsNull() {
            addCriterion("id_card_no is null");
            return (Criteria) this;
        }

        public Criteria andIdCardNoIsNotNull() {
            addCriterion("id_card_no is not null");
            return (Criteria) this;
        }

        public Criteria andIdCardNoEqualTo(String value) {
            addCriterion("id_card_no =", value, "idCardNo");
            return (Criteria) this;
        }

        public Criteria andIdCardNoNotEqualTo(String value) {
            addCriterion("id_card_no <>", value, "idCardNo");
            return (Criteria) this;
        }

        public Criteria andIdCardNoGreaterThan(String value) {
            addCriterion("id_card_no >", value, "idCardNo");
            return (Criteria) this;
        }

        public Criteria andIdCardNoGreaterThanOrEqualTo(String value) {
            addCriterion("id_card_no >=", value, "idCardNo");
            return (Criteria) this;
        }

        public Criteria andIdCardNoLessThan(String value) {
            addCriterion("id_card_no <", value, "idCardNo");
            return (Criteria) this;
        }

        public Criteria andIdCardNoLessThanOrEqualTo(String value) {
            addCriterion("id_card_no <=", value, "idCardNo");
            return (Criteria) this;
        }

        public Criteria andIdCardNoLike(String value) {
            addCriterion("id_card_no like", value, "idCardNo");
            return (Criteria) this;
        }

        public Criteria andIdCardNoNotLike(String value) {
            addCriterion("id_card_no not like", value, "idCardNo");
            return (Criteria) this;
        }

        public Criteria andIdCardNoIn(List<String> values) {
            addCriterion("id_card_no in", values, "idCardNo");
            return (Criteria) this;
        }

        public Criteria andIdCardNoNotIn(List<String> values) {
            addCriterion("id_card_no not in", values, "idCardNo");
            return (Criteria) this;
        }

        public Criteria andIdCardNoBetween(String value1, String value2) {
            addCriterion("id_card_no between", value1, value2, "idCardNo");
            return (Criteria) this;
        }

        public Criteria andIdCardNoNotBetween(String value1, String value2) {
            addCriterion("id_card_no not between", value1, value2, "idCardNo");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andRegSourceIsNull() {
            addCriterion("reg_source is null");
            return (Criteria) this;
        }

        public Criteria andRegSourceIsNotNull() {
            addCriterion("reg_source is not null");
            return (Criteria) this;
        }

        public Criteria andRegSourceEqualTo(String value) {
            addCriterion("reg_source =", value, "regSource");
            return (Criteria) this;
        }

        public Criteria andRegSourceNotEqualTo(String value) {
            addCriterion("reg_source <>", value, "regSource");
            return (Criteria) this;
        }

        public Criteria andRegSourceGreaterThan(String value) {
            addCriterion("reg_source >", value, "regSource");
            return (Criteria) this;
        }

        public Criteria andRegSourceGreaterThanOrEqualTo(String value) {
            addCriterion("reg_source >=", value, "regSource");
            return (Criteria) this;
        }

        public Criteria andRegSourceLessThan(String value) {
            addCriterion("reg_source <", value, "regSource");
            return (Criteria) this;
        }

        public Criteria andRegSourceLessThanOrEqualTo(String value) {
            addCriterion("reg_source <=", value, "regSource");
            return (Criteria) this;
        }

        public Criteria andRegSourceLike(String value) {
            addCriterion("reg_source like", value, "regSource");
            return (Criteria) this;
        }

        public Criteria andRegSourceNotLike(String value) {
            addCriterion("reg_source not like", value, "regSource");
            return (Criteria) this;
        }

        public Criteria andRegSourceIn(List<String> values) {
            addCriterion("reg_source in", values, "regSource");
            return (Criteria) this;
        }

        public Criteria andRegSourceNotIn(List<String> values) {
            addCriterion("reg_source not in", values, "regSource");
            return (Criteria) this;
        }

        public Criteria andRegSourceBetween(String value1, String value2) {
            addCriterion("reg_source between", value1, value2, "regSource");
            return (Criteria) this;
        }

        public Criteria andRegSourceNotBetween(String value1, String value2) {
            addCriterion("reg_source not between", value1, value2, "regSource");
            return (Criteria) this;
        }

        public Criteria andRegPlatformIsNull() {
            addCriterion("reg_platform is null");
            return (Criteria) this;
        }

        public Criteria andRegPlatformIsNotNull() {
            addCriterion("reg_platform is not null");
            return (Criteria) this;
        }

        public Criteria andRegPlatformEqualTo(String value) {
            addCriterion("reg_platform =", value, "regPlatform");
            return (Criteria) this;
        }

        public Criteria andRegPlatformNotEqualTo(String value) {
            addCriterion("reg_platform <>", value, "regPlatform");
            return (Criteria) this;
        }

        public Criteria andRegPlatformGreaterThan(String value) {
            addCriterion("reg_platform >", value, "regPlatform");
            return (Criteria) this;
        }

        public Criteria andRegPlatformGreaterThanOrEqualTo(String value) {
            addCriterion("reg_platform >=", value, "regPlatform");
            return (Criteria) this;
        }

        public Criteria andRegPlatformLessThan(String value) {
            addCriterion("reg_platform <", value, "regPlatform");
            return (Criteria) this;
        }

        public Criteria andRegPlatformLessThanOrEqualTo(String value) {
            addCriterion("reg_platform <=", value, "regPlatform");
            return (Criteria) this;
        }

        public Criteria andRegPlatformLike(String value) {
            addCriterion("reg_platform like", value, "regPlatform");
            return (Criteria) this;
        }

        public Criteria andRegPlatformNotLike(String value) {
            addCriterion("reg_platform not like", value, "regPlatform");
            return (Criteria) this;
        }

        public Criteria andRegPlatformIn(List<String> values) {
            addCriterion("reg_platform in", values, "regPlatform");
            return (Criteria) this;
        }

        public Criteria andRegPlatformNotIn(List<String> values) {
            addCriterion("reg_platform not in", values, "regPlatform");
            return (Criteria) this;
        }

        public Criteria andRegPlatformBetween(String value1, String value2) {
            addCriterion("reg_platform between", value1, value2, "regPlatform");
            return (Criteria) this;
        }

        public Criteria andRegPlatformNotBetween(String value1, String value2) {
            addCriterion("reg_platform not between", value1, value2, "regPlatform");
            return (Criteria) this;
        }

        public Criteria andDeviceIsNull() {
            addCriterion("device is null");
            return (Criteria) this;
        }

        public Criteria andDeviceIsNotNull() {
            addCriterion("device is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceEqualTo(String value) {
            addCriterion("device =", value, "device");
            return (Criteria) this;
        }

        public Criteria andDeviceNotEqualTo(String value) {
            addCriterion("device <>", value, "device");
            return (Criteria) this;
        }

        public Criteria andDeviceGreaterThan(String value) {
            addCriterion("device >", value, "device");
            return (Criteria) this;
        }

        public Criteria andDeviceGreaterThanOrEqualTo(String value) {
            addCriterion("device >=", value, "device");
            return (Criteria) this;
        }

        public Criteria andDeviceLessThan(String value) {
            addCriterion("device <", value, "device");
            return (Criteria) this;
        }

        public Criteria andDeviceLessThanOrEqualTo(String value) {
            addCriterion("device <=", value, "device");
            return (Criteria) this;
        }

        public Criteria andDeviceLike(String value) {
            addCriterion("device like", value, "device");
            return (Criteria) this;
        }

        public Criteria andDeviceNotLike(String value) {
            addCriterion("device not like", value, "device");
            return (Criteria) this;
        }

        public Criteria andDeviceIn(List<String> values) {
            addCriterion("device in", values, "device");
            return (Criteria) this;
        }

        public Criteria andDeviceNotIn(List<String> values) {
            addCriterion("device not in", values, "device");
            return (Criteria) this;
        }

        public Criteria andDeviceBetween(String value1, String value2) {
            addCriterion("device between", value1, value2, "device");
            return (Criteria) this;
        }

        public Criteria andDeviceNotBetween(String value1, String value2) {
            addCriterion("device not between", value1, value2, "device");
            return (Criteria) this;
        }

        public Criteria andIsStockIsNull() {
            addCriterion("is_stock is null");
            return (Criteria) this;
        }

        public Criteria andIsStockIsNotNull() {
            addCriterion("is_stock is not null");
            return (Criteria) this;
        }

        public Criteria andIsStockEqualTo(String value) {
            addCriterion("is_stock =", value, "isStock");
            return (Criteria) this;
        }

        public Criteria andIsStockNotEqualTo(String value) {
            addCriterion("is_stock <>", value, "isStock");
            return (Criteria) this;
        }

        public Criteria andIsStockGreaterThan(String value) {
            addCriterion("is_stock >", value, "isStock");
            return (Criteria) this;
        }

        public Criteria andIsStockGreaterThanOrEqualTo(String value) {
            addCriterion("is_stock >=", value, "isStock");
            return (Criteria) this;
        }

        public Criteria andIsStockLessThan(String value) {
            addCriterion("is_stock <", value, "isStock");
            return (Criteria) this;
        }

        public Criteria andIsStockLessThanOrEqualTo(String value) {
            addCriterion("is_stock <=", value, "isStock");
            return (Criteria) this;
        }

        public Criteria andIsStockLike(String value) {
            addCriterion("is_stock like", value, "isStock");
            return (Criteria) this;
        }

        public Criteria andIsStockNotLike(String value) {
            addCriterion("is_stock not like", value, "isStock");
            return (Criteria) this;
        }

        public Criteria andIsStockIn(List<String> values) {
            addCriterion("is_stock in", values, "isStock");
            return (Criteria) this;
        }

        public Criteria andIsStockNotIn(List<String> values) {
            addCriterion("is_stock not in", values, "isStock");
            return (Criteria) this;
        }

        public Criteria andIsStockBetween(String value1, String value2) {
            addCriterion("is_stock between", value1, value2, "isStock");
            return (Criteria) this;
        }

        public Criteria andIsStockNotBetween(String value1, String value2) {
            addCriterion("is_stock not between", value1, value2, "isStock");
            return (Criteria) this;
        }

        public Criteria andStockStatusIsNull() {
            addCriterion("stock_status is null");
            return (Criteria) this;
        }

        public Criteria andStockStatusIsNotNull() {
            addCriterion("stock_status is not null");
            return (Criteria) this;
        }

        public Criteria andStockStatusEqualTo(String value) {
            addCriterion("stock_status =", value, "stockStatus");
            return (Criteria) this;
        }

        public Criteria andStockStatusNotEqualTo(String value) {
            addCriterion("stock_status <>", value, "stockStatus");
            return (Criteria) this;
        }

        public Criteria andStockStatusGreaterThan(String value) {
            addCriterion("stock_status >", value, "stockStatus");
            return (Criteria) this;
        }

        public Criteria andStockStatusGreaterThanOrEqualTo(String value) {
            addCriterion("stock_status >=", value, "stockStatus");
            return (Criteria) this;
        }

        public Criteria andStockStatusLessThan(String value) {
            addCriterion("stock_status <", value, "stockStatus");
            return (Criteria) this;
        }

        public Criteria andStockStatusLessThanOrEqualTo(String value) {
            addCriterion("stock_status <=", value, "stockStatus");
            return (Criteria) this;
        }

        public Criteria andStockStatusLike(String value) {
            addCriterion("stock_status like", value, "stockStatus");
            return (Criteria) this;
        }

        public Criteria andStockStatusNotLike(String value) {
            addCriterion("stock_status not like", value, "stockStatus");
            return (Criteria) this;
        }

        public Criteria andStockStatusIn(List<String> values) {
            addCriterion("stock_status in", values, "stockStatus");
            return (Criteria) this;
        }

        public Criteria andStockStatusNotIn(List<String> values) {
            addCriterion("stock_status not in", values, "stockStatus");
            return (Criteria) this;
        }

        public Criteria andStockStatusBetween(String value1, String value2) {
            addCriterion("stock_status between", value1, value2, "stockStatus");
            return (Criteria) this;
        }

        public Criteria andStockStatusNotBetween(String value1, String value2) {
            addCriterion("stock_status not between", value1, value2, "stockStatus");
            return (Criteria) this;
        }

        public Criteria andIsOpenAccountIsNull() {
            addCriterion("is_open_account is null");
            return (Criteria) this;
        }

        public Criteria andIsOpenAccountIsNotNull() {
            addCriterion("is_open_account is not null");
            return (Criteria) this;
        }

        public Criteria andIsOpenAccountEqualTo(String value) {
            addCriterion("is_open_account =", value, "isOpenAccount");
            return (Criteria) this;
        }

        public Criteria andIsOpenAccountNotEqualTo(String value) {
            addCriterion("is_open_account <>", value, "isOpenAccount");
            return (Criteria) this;
        }

        public Criteria andIsOpenAccountGreaterThan(String value) {
            addCriterion("is_open_account >", value, "isOpenAccount");
            return (Criteria) this;
        }

        public Criteria andIsOpenAccountGreaterThanOrEqualTo(String value) {
            addCriterion("is_open_account >=", value, "isOpenAccount");
            return (Criteria) this;
        }

        public Criteria andIsOpenAccountLessThan(String value) {
            addCriterion("is_open_account <", value, "isOpenAccount");
            return (Criteria) this;
        }

        public Criteria andIsOpenAccountLessThanOrEqualTo(String value) {
            addCriterion("is_open_account <=", value, "isOpenAccount");
            return (Criteria) this;
        }

        public Criteria andIsOpenAccountLike(String value) {
            addCriterion("is_open_account like", value, "isOpenAccount");
            return (Criteria) this;
        }

        public Criteria andIsOpenAccountNotLike(String value) {
            addCriterion("is_open_account not like", value, "isOpenAccount");
            return (Criteria) this;
        }

        public Criteria andIsOpenAccountIn(List<String> values) {
            addCriterion("is_open_account in", values, "isOpenAccount");
            return (Criteria) this;
        }

        public Criteria andIsOpenAccountNotIn(List<String> values) {
            addCriterion("is_open_account not in", values, "isOpenAccount");
            return (Criteria) this;
        }

        public Criteria andIsOpenAccountBetween(String value1, String value2) {
            addCriterion("is_open_account between", value1, value2, "isOpenAccount");
            return (Criteria) this;
        }

        public Criteria andIsOpenAccountNotBetween(String value1, String value2) {
            addCriterion("is_open_account not between", value1, value2, "isOpenAccount");
            return (Criteria) this;
        }

        public Criteria andRegTimeIsNull() {
            addCriterion("reg_time is null");
            return (Criteria) this;
        }

        public Criteria andRegTimeIsNotNull() {
            addCriterion("reg_time is not null");
            return (Criteria) this;
        }

        public Criteria andRegTimeEqualTo(Date value) {
            addCriterion("reg_time =", value, "regTime");
            return (Criteria) this;
        }

        public Criteria andRegTimeNotEqualTo(Date value) {
            addCriterion("reg_time <>", value, "regTime");
            return (Criteria) this;
        }

        public Criteria andRegTimeGreaterThan(Date value) {
            addCriterion("reg_time >", value, "regTime");
            return (Criteria) this;
        }

        public Criteria andRegTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("reg_time >=", value, "regTime");
            return (Criteria) this;
        }

        public Criteria andRegTimeLessThan(Date value) {
            addCriterion("reg_time <", value, "regTime");
            return (Criteria) this;
        }

        public Criteria andRegTimeLessThanOrEqualTo(Date value) {
            addCriterion("reg_time <=", value, "regTime");
            return (Criteria) this;
        }

        public Criteria andRegTimeIn(List<Date> values) {
            addCriterion("reg_time in", values, "regTime");
            return (Criteria) this;
        }

        public Criteria andRegTimeNotIn(List<Date> values) {
            addCriterion("reg_time not in", values, "regTime");
            return (Criteria) this;
        }

        public Criteria andRegTimeBetween(Date value1, Date value2) {
            addCriterion("reg_time between", value1, value2, "regTime");
            return (Criteria) this;
        }

        public Criteria andRegTimeNotBetween(Date value1, Date value2) {
            addCriterion("reg_time not between", value1, value2, "regTime");
            return (Criteria) this;
        }

        public Criteria andLevelIsNull() {
            addCriterion("level is null");
            return (Criteria) this;
        }

        public Criteria andLevelIsNotNull() {
            addCriterion("level is not null");
            return (Criteria) this;
        }

        public Criteria andLevelEqualTo(String value) {
            addCriterion("level =", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotEqualTo(String value) {
            addCriterion("level <>", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThan(String value) {
            addCriterion("level >", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThanOrEqualTo(String value) {
            addCriterion("level >=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThan(String value) {
            addCriterion("level <", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThanOrEqualTo(String value) {
            addCriterion("level <=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLike(String value) {
            addCriterion("level like", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotLike(String value) {
            addCriterion("level not like", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelIn(List<String> values) {
            addCriterion("level in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotIn(List<String> values) {
            addCriterion("level not in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelBetween(String value1, String value2) {
            addCriterion("level between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotBetween(String value1, String value2) {
            addCriterion("level not between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andGrowthNumIsNull() {
            addCriterion("growth_num is null");
            return (Criteria) this;
        }

        public Criteria andGrowthNumIsNotNull() {
            addCriterion("growth_num is not null");
            return (Criteria) this;
        }

        public Criteria andGrowthNumEqualTo(Long value) {
            addCriterion("growth_num =", value, "growthNum");
            return (Criteria) this;
        }

        public Criteria andGrowthNumNotEqualTo(Long value) {
            addCriterion("growth_num <>", value, "growthNum");
            return (Criteria) this;
        }

        public Criteria andGrowthNumGreaterThan(Long value) {
            addCriterion("growth_num >", value, "growthNum");
            return (Criteria) this;
        }

        public Criteria andGrowthNumGreaterThanOrEqualTo(Long value) {
            addCriterion("growth_num >=", value, "growthNum");
            return (Criteria) this;
        }

        public Criteria andGrowthNumLessThan(Long value) {
            addCriterion("growth_num <", value, "growthNum");
            return (Criteria) this;
        }

        public Criteria andGrowthNumLessThanOrEqualTo(Long value) {
            addCriterion("growth_num <=", value, "growthNum");
            return (Criteria) this;
        }

        public Criteria andGrowthNumIn(List<Long> values) {
            addCriterion("growth_num in", values, "growthNum");
            return (Criteria) this;
        }

        public Criteria andGrowthNumNotIn(List<Long> values) {
            addCriterion("growth_num not in", values, "growthNum");
            return (Criteria) this;
        }

        public Criteria andGrowthNumBetween(Long value1, Long value2) {
            addCriterion("growth_num between", value1, value2, "growthNum");
            return (Criteria) this;
        }

        public Criteria andGrowthNumNotBetween(Long value1, Long value2) {
            addCriterion("growth_num not between", value1, value2, "growthNum");
            return (Criteria) this;
        }

        public Criteria andCoinNumIsNull() {
            addCriterion("coin_num is null");
            return (Criteria) this;
        }

        public Criteria andCoinNumIsNotNull() {
            addCriterion("coin_num is not null");
            return (Criteria) this;
        }

        public Criteria andCoinNumEqualTo(Long value) {
            addCriterion("coin_num =", value, "coinNum");
            return (Criteria) this;
        }

        public Criteria andCoinNumNotEqualTo(Long value) {
            addCriterion("coin_num <>", value, "coinNum");
            return (Criteria) this;
        }

        public Criteria andCoinNumGreaterThan(Long value) {
            addCriterion("coin_num >", value, "coinNum");
            return (Criteria) this;
        }

        public Criteria andCoinNumGreaterThanOrEqualTo(Long value) {
            addCriterion("coin_num >=", value, "coinNum");
            return (Criteria) this;
        }

        public Criteria andCoinNumLessThan(Long value) {
            addCriterion("coin_num <", value, "coinNum");
            return (Criteria) this;
        }

        public Criteria andCoinNumLessThanOrEqualTo(Long value) {
            addCriterion("coin_num <=", value, "coinNum");
            return (Criteria) this;
        }

        public Criteria andCoinNumIn(List<Long> values) {
            addCriterion("coin_num in", values, "coinNum");
            return (Criteria) this;
        }

        public Criteria andCoinNumNotIn(List<Long> values) {
            addCriterion("coin_num not in", values, "coinNum");
            return (Criteria) this;
        }

        public Criteria andCoinNumBetween(Long value1, Long value2) {
            addCriterion("coin_num between", value1, value2, "coinNum");
            return (Criteria) this;
        }

        public Criteria andCoinNumNotBetween(Long value1, Long value2) {
            addCriterion("coin_num not between", value1, value2, "coinNum");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("sex is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("sex is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(String value) {
            addCriterion("sex =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(String value) {
            addCriterion("sex <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(String value) {
            addCriterion("sex >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(String value) {
            addCriterion("sex >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(String value) {
            addCriterion("sex <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(String value) {
            addCriterion("sex <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLike(String value) {
            addCriterion("sex like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotLike(String value) {
            addCriterion("sex not like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<String> values) {
            addCriterion("sex in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<String> values) {
            addCriterion("sex not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(String value1, String value2) {
            addCriterion("sex between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(String value1, String value2) {
            addCriterion("sex not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andEmailCheckIsNull() {
            addCriterion("email_check is null");
            return (Criteria) this;
        }

        public Criteria andEmailCheckIsNotNull() {
            addCriterion("email_check is not null");
            return (Criteria) this;
        }

        public Criteria andEmailCheckEqualTo(String value) {
            addCriterion("email_check =", value, "emailCheck");
            return (Criteria) this;
        }

        public Criteria andEmailCheckNotEqualTo(String value) {
            addCriterion("email_check <>", value, "emailCheck");
            return (Criteria) this;
        }

        public Criteria andEmailCheckGreaterThan(String value) {
            addCriterion("email_check >", value, "emailCheck");
            return (Criteria) this;
        }

        public Criteria andEmailCheckGreaterThanOrEqualTo(String value) {
            addCriterion("email_check >=", value, "emailCheck");
            return (Criteria) this;
        }

        public Criteria andEmailCheckLessThan(String value) {
            addCriterion("email_check <", value, "emailCheck");
            return (Criteria) this;
        }

        public Criteria andEmailCheckLessThanOrEqualTo(String value) {
            addCriterion("email_check <=", value, "emailCheck");
            return (Criteria) this;
        }

        public Criteria andEmailCheckLike(String value) {
            addCriterion("email_check like", value, "emailCheck");
            return (Criteria) this;
        }

        public Criteria andEmailCheckNotLike(String value) {
            addCriterion("email_check not like", value, "emailCheck");
            return (Criteria) this;
        }

        public Criteria andEmailCheckIn(List<String> values) {
            addCriterion("email_check in", values, "emailCheck");
            return (Criteria) this;
        }

        public Criteria andEmailCheckNotIn(List<String> values) {
            addCriterion("email_check not in", values, "emailCheck");
            return (Criteria) this;
        }

        public Criteria andEmailCheckBetween(String value1, String value2) {
            addCriterion("email_check between", value1, value2, "emailCheck");
            return (Criteria) this;
        }

        public Criteria andEmailCheckNotBetween(String value1, String value2) {
            addCriterion("email_check not between", value1, value2, "emailCheck");
            return (Criteria) this;
        }

        public Criteria andOpenTimeIsNull() {
            addCriterion("open_time is null");
            return (Criteria) this;
        }

        public Criteria andOpenTimeIsNotNull() {
            addCriterion("open_time is not null");
            return (Criteria) this;
        }

        public Criteria andOpenTimeEqualTo(Date value) {
            addCriterion("open_time =", value, "openTime");
            return (Criteria) this;
        }

        public Criteria andOpenTimeNotEqualTo(Date value) {
            addCriterion("open_time <>", value, "openTime");
            return (Criteria) this;
        }

        public Criteria andOpenTimeGreaterThan(Date value) {
            addCriterion("open_time >", value, "openTime");
            return (Criteria) this;
        }

        public Criteria andOpenTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("open_time >=", value, "openTime");
            return (Criteria) this;
        }

        public Criteria andOpenTimeLessThan(Date value) {
            addCriterion("open_time <", value, "openTime");
            return (Criteria) this;
        }

        public Criteria andOpenTimeLessThanOrEqualTo(Date value) {
            addCriterion("open_time <=", value, "openTime");
            return (Criteria) this;
        }

        public Criteria andOpenTimeIn(List<Date> values) {
            addCriterion("open_time in", values, "openTime");
            return (Criteria) this;
        }

        public Criteria andOpenTimeNotIn(List<Date> values) {
            addCriterion("open_time not in", values, "openTime");
            return (Criteria) this;
        }

        public Criteria andOpenTimeBetween(Date value1, Date value2) {
            addCriterion("open_time between", value1, value2, "openTime");
            return (Criteria) this;
        }

        public Criteria andOpenTimeNotBetween(Date value1, Date value2) {
            addCriterion("open_time not between", value1, value2, "openTime");
            return (Criteria) this;
        }

        public Criteria andIsNewIsNull() {
            addCriterion("is_new is null");
            return (Criteria) this;
        }

        public Criteria andIsNewIsNotNull() {
            addCriterion("is_new is not null");
            return (Criteria) this;
        }

        public Criteria andIsNewEqualTo(String value) {
            addCriterion("is_new =", value, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsNewNotEqualTo(String value) {
            addCriterion("is_new <>", value, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsNewGreaterThan(String value) {
            addCriterion("is_new >", value, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsNewGreaterThanOrEqualTo(String value) {
            addCriterion("is_new >=", value, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsNewLessThan(String value) {
            addCriterion("is_new <", value, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsNewLessThanOrEqualTo(String value) {
            addCriterion("is_new <=", value, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsNewLike(String value) {
            addCriterion("is_new like", value, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsNewNotLike(String value) {
            addCriterion("is_new not like", value, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsNewIn(List<String> values) {
            addCriterion("is_new in", values, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsNewNotIn(List<String> values) {
            addCriterion("is_new not in", values, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsNewBetween(String value1, String value2) {
            addCriterion("is_new between", value1, value2, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsNewNotBetween(String value1, String value2) {
            addCriterion("is_new not between", value1, value2, "isNew");
            return (Criteria) this;
        }

        public Criteria andGuaranteeCodeIsNull() {
            addCriterion("guarantee_code is null");
            return (Criteria) this;
        }

        public Criteria andGuaranteeCodeIsNotNull() {
            addCriterion("guarantee_code is not null");
            return (Criteria) this;
        }

        public Criteria andGuaranteeCodeEqualTo(String value) {
            addCriterion("guarantee_code =", value, "guaranteeCode");
            return (Criteria) this;
        }

        public Criteria andGuaranteeCodeNotEqualTo(String value) {
            addCriterion("guarantee_code <>", value, "guaranteeCode");
            return (Criteria) this;
        }

        public Criteria andGuaranteeCodeGreaterThan(String value) {
            addCriterion("guarantee_code >", value, "guaranteeCode");
            return (Criteria) this;
        }

        public Criteria andGuaranteeCodeGreaterThanOrEqualTo(String value) {
            addCriterion("guarantee_code >=", value, "guaranteeCode");
            return (Criteria) this;
        }

        public Criteria andGuaranteeCodeLessThan(String value) {
            addCriterion("guarantee_code <", value, "guaranteeCode");
            return (Criteria) this;
        }

        public Criteria andGuaranteeCodeLessThanOrEqualTo(String value) {
            addCriterion("guarantee_code <=", value, "guaranteeCode");
            return (Criteria) this;
        }

        public Criteria andGuaranteeCodeLike(String value) {
            addCriterion("guarantee_code like", value, "guaranteeCode");
            return (Criteria) this;
        }

        public Criteria andGuaranteeCodeNotLike(String value) {
            addCriterion("guarantee_code not like", value, "guaranteeCode");
            return (Criteria) this;
        }

        public Criteria andGuaranteeCodeIn(List<String> values) {
            addCriterion("guarantee_code in", values, "guaranteeCode");
            return (Criteria) this;
        }

        public Criteria andGuaranteeCodeNotIn(List<String> values) {
            addCriterion("guarantee_code not in", values, "guaranteeCode");
            return (Criteria) this;
        }

        public Criteria andGuaranteeCodeBetween(String value1, String value2) {
            addCriterion("guarantee_code between", value1, value2, "guaranteeCode");
            return (Criteria) this;
        }

        public Criteria andGuaranteeCodeNotBetween(String value1, String value2) {
            addCriterion("guarantee_code not between", value1, value2, "guaranteeCode");
            return (Criteria) this;
        }

        public Criteria andInviteCodeIsNull() {
            addCriterion("invite_code is null");
            return (Criteria) this;
        }

        public Criteria andInviteCodeIsNotNull() {
            addCriterion("invite_code is not null");
            return (Criteria) this;
        }

        public Criteria andInviteCodeEqualTo(String value) {
            addCriterion("invite_code =", value, "inviteCode");
            return (Criteria) this;
        }

        public Criteria andInviteCodeNotEqualTo(String value) {
            addCriterion("invite_code <>", value, "inviteCode");
            return (Criteria) this;
        }

        public Criteria andInviteCodeGreaterThan(String value) {
            addCriterion("invite_code >", value, "inviteCode");
            return (Criteria) this;
        }

        public Criteria andInviteCodeGreaterThanOrEqualTo(String value) {
            addCriterion("invite_code >=", value, "inviteCode");
            return (Criteria) this;
        }

        public Criteria andInviteCodeLessThan(String value) {
            addCriterion("invite_code <", value, "inviteCode");
            return (Criteria) this;
        }

        public Criteria andInviteCodeLessThanOrEqualTo(String value) {
            addCriterion("invite_code <=", value, "inviteCode");
            return (Criteria) this;
        }

        public Criteria andInviteCodeLike(String value) {
            addCriterion("invite_code like", value, "inviteCode");
            return (Criteria) this;
        }

        public Criteria andInviteCodeNotLike(String value) {
            addCriterion("invite_code not like", value, "inviteCode");
            return (Criteria) this;
        }

        public Criteria andInviteCodeIn(List<String> values) {
            addCriterion("invite_code in", values, "inviteCode");
            return (Criteria) this;
        }

        public Criteria andInviteCodeNotIn(List<String> values) {
            addCriterion("invite_code not in", values, "inviteCode");
            return (Criteria) this;
        }

        public Criteria andInviteCodeBetween(String value1, String value2) {
            addCriterion("invite_code between", value1, value2, "inviteCode");
            return (Criteria) this;
        }

        public Criteria andInviteCodeNotBetween(String value1, String value2) {
            addCriterion("invite_code not between", value1, value2, "inviteCode");
            return (Criteria) this;
        }

        public Criteria andMyInviteCodeIsNull() {
            addCriterion("my_invite_code is null");
            return (Criteria) this;
        }

        public Criteria andMyInviteCodeIsNotNull() {
            addCriterion("my_invite_code is not null");
            return (Criteria) this;
        }

        public Criteria andMyInviteCodeEqualTo(String value) {
            addCriterion("my_invite_code =", value, "myInviteCode");
            return (Criteria) this;
        }

        public Criteria andMyInviteCodeNotEqualTo(String value) {
            addCriterion("my_invite_code <>", value, "myInviteCode");
            return (Criteria) this;
        }

        public Criteria andMyInviteCodeGreaterThan(String value) {
            addCriterion("my_invite_code >", value, "myInviteCode");
            return (Criteria) this;
        }

        public Criteria andMyInviteCodeGreaterThanOrEqualTo(String value) {
            addCriterion("my_invite_code >=", value, "myInviteCode");
            return (Criteria) this;
        }

        public Criteria andMyInviteCodeLessThan(String value) {
            addCriterion("my_invite_code <", value, "myInviteCode");
            return (Criteria) this;
        }

        public Criteria andMyInviteCodeLessThanOrEqualTo(String value) {
            addCriterion("my_invite_code <=", value, "myInviteCode");
            return (Criteria) this;
        }

        public Criteria andMyInviteCodeLike(String value) {
            addCriterion("my_invite_code like", value, "myInviteCode");
            return (Criteria) this;
        }

        public Criteria andMyInviteCodeNotLike(String value) {
            addCriterion("my_invite_code not like", value, "myInviteCode");
            return (Criteria) this;
        }

        public Criteria andMyInviteCodeIn(List<String> values) {
            addCriterion("my_invite_code in", values, "myInviteCode");
            return (Criteria) this;
        }

        public Criteria andMyInviteCodeNotIn(List<String> values) {
            addCriterion("my_invite_code not in", values, "myInviteCode");
            return (Criteria) this;
        }

        public Criteria andMyInviteCodeBetween(String value1, String value2) {
            addCriterion("my_invite_code between", value1, value2, "myInviteCode");
            return (Criteria) this;
        }

        public Criteria andMyInviteCodeNotBetween(String value1, String value2) {
            addCriterion("my_invite_code not between", value1, value2, "myInviteCode");
            return (Criteria) this;
        }

        public Criteria andAvailableAmountIsNull() {
            addCriterion("available_amount is null");
            return (Criteria) this;
        }

        public Criteria andAvailableAmountIsNotNull() {
            addCriterion("available_amount is not null");
            return (Criteria) this;
        }

        public Criteria andAvailableAmountEqualTo(BigDecimal value) {
            addCriterion("available_amount =", value, "availableAmount");
            return (Criteria) this;
        }

        public Criteria andAvailableAmountNotEqualTo(BigDecimal value) {
            addCriterion("available_amount <>", value, "availableAmount");
            return (Criteria) this;
        }

        public Criteria andAvailableAmountGreaterThan(BigDecimal value) {
            addCriterion("available_amount >", value, "availableAmount");
            return (Criteria) this;
        }

        public Criteria andAvailableAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("available_amount >=", value, "availableAmount");
            return (Criteria) this;
        }

        public Criteria andAvailableAmountLessThan(BigDecimal value) {
            addCriterion("available_amount <", value, "availableAmount");
            return (Criteria) this;
        }

        public Criteria andAvailableAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("available_amount <=", value, "availableAmount");
            return (Criteria) this;
        }

        public Criteria andAvailableAmountIn(List<BigDecimal> values) {
            addCriterion("available_amount in", values, "availableAmount");
            return (Criteria) this;
        }

        public Criteria andAvailableAmountNotIn(List<BigDecimal> values) {
            addCriterion("available_amount not in", values, "availableAmount");
            return (Criteria) this;
        }

        public Criteria andAvailableAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("available_amount between", value1, value2, "availableAmount");
            return (Criteria) this;
        }

        public Criteria andAvailableAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("available_amount not between", value1, value2, "availableAmount");
            return (Criteria) this;
        }

        public Criteria andTokenValideTimeIsNull() {
            addCriterion("token_valide_time is null");
            return (Criteria) this;
        }

        public Criteria andTokenValideTimeIsNotNull() {
            addCriterion("token_valide_time is not null");
            return (Criteria) this;
        }

        public Criteria andTokenValideTimeEqualTo(Integer value) {
            addCriterion("token_valide_time =", value, "tokenValideTime");
            return (Criteria) this;
        }

        public Criteria andTokenValideTimeNotEqualTo(Integer value) {
            addCriterion("token_valide_time <>", value, "tokenValideTime");
            return (Criteria) this;
        }

        public Criteria andTokenValideTimeGreaterThan(Integer value) {
            addCriterion("token_valide_time >", value, "tokenValideTime");
            return (Criteria) this;
        }

        public Criteria andTokenValideTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("token_valide_time >=", value, "tokenValideTime");
            return (Criteria) this;
        }

        public Criteria andTokenValideTimeLessThan(Integer value) {
            addCriterion("token_valide_time <", value, "tokenValideTime");
            return (Criteria) this;
        }

        public Criteria andTokenValideTimeLessThanOrEqualTo(Integer value) {
            addCriterion("token_valide_time <=", value, "tokenValideTime");
            return (Criteria) this;
        }

        public Criteria andTokenValideTimeIn(List<Integer> values) {
            addCriterion("token_valide_time in", values, "tokenValideTime");
            return (Criteria) this;
        }

        public Criteria andTokenValideTimeNotIn(List<Integer> values) {
            addCriterion("token_valide_time not in", values, "tokenValideTime");
            return (Criteria) this;
        }

        public Criteria andTokenValideTimeBetween(Integer value1, Integer value2) {
            addCriterion("token_valide_time between", value1, value2, "tokenValideTime");
            return (Criteria) this;
        }

        public Criteria andTokenValideTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("token_valide_time not between", value1, value2, "tokenValideTime");
            return (Criteria) this;
        }

        public Criteria andEmailBindTimeIsNull() {
            addCriterion("email_bind_time is null");
            return (Criteria) this;
        }

        public Criteria andEmailBindTimeIsNotNull() {
            addCriterion("email_bind_time is not null");
            return (Criteria) this;
        }

        public Criteria andEmailBindTimeEqualTo(Date value) {
            addCriterion("email_bind_time =", value, "emailBindTime");
            return (Criteria) this;
        }

        public Criteria andEmailBindTimeNotEqualTo(Date value) {
            addCriterion("email_bind_time <>", value, "emailBindTime");
            return (Criteria) this;
        }

        public Criteria andEmailBindTimeGreaterThan(Date value) {
            addCriterion("email_bind_time >", value, "emailBindTime");
            return (Criteria) this;
        }

        public Criteria andEmailBindTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("email_bind_time >=", value, "emailBindTime");
            return (Criteria) this;
        }

        public Criteria andEmailBindTimeLessThan(Date value) {
            addCriterion("email_bind_time <", value, "emailBindTime");
            return (Criteria) this;
        }

        public Criteria andEmailBindTimeLessThanOrEqualTo(Date value) {
            addCriterion("email_bind_time <=", value, "emailBindTime");
            return (Criteria) this;
        }

        public Criteria andEmailBindTimeIn(List<Date> values) {
            addCriterion("email_bind_time in", values, "emailBindTime");
            return (Criteria) this;
        }

        public Criteria andEmailBindTimeNotIn(List<Date> values) {
            addCriterion("email_bind_time not in", values, "emailBindTime");
            return (Criteria) this;
        }

        public Criteria andEmailBindTimeBetween(Date value1, Date value2) {
            addCriterion("email_bind_time between", value1, value2, "emailBindTime");
            return (Criteria) this;
        }

        public Criteria andEmailBindTimeNotBetween(Date value1, Date value2) {
            addCriterion("email_bind_time not between", value1, value2, "emailBindTime");
            return (Criteria) this;
        }

        public Criteria andIsPassRiskRatingIsNull() {
            addCriterion("is_pass_risk_rating is null");
            return (Criteria) this;
        }

        public Criteria andIsPassRiskRatingIsNotNull() {
            addCriterion("is_pass_risk_rating is not null");
            return (Criteria) this;
        }

        public Criteria andIsPassRiskRatingEqualTo(String value) {
            addCriterion("is_pass_risk_rating =", value, "isPassRiskRating");
            return (Criteria) this;
        }

        public Criteria andIsPassRiskRatingNotEqualTo(String value) {
            addCriterion("is_pass_risk_rating <>", value, "isPassRiskRating");
            return (Criteria) this;
        }

        public Criteria andIsPassRiskRatingGreaterThan(String value) {
            addCriterion("is_pass_risk_rating >", value, "isPassRiskRating");
            return (Criteria) this;
        }

        public Criteria andIsPassRiskRatingGreaterThanOrEqualTo(String value) {
            addCriterion("is_pass_risk_rating >=", value, "isPassRiskRating");
            return (Criteria) this;
        }

        public Criteria andIsPassRiskRatingLessThan(String value) {
            addCriterion("is_pass_risk_rating <", value, "isPassRiskRating");
            return (Criteria) this;
        }

        public Criteria andIsPassRiskRatingLessThanOrEqualTo(String value) {
            addCriterion("is_pass_risk_rating <=", value, "isPassRiskRating");
            return (Criteria) this;
        }

        public Criteria andIsPassRiskRatingLike(String value) {
            addCriterion("is_pass_risk_rating like", value, "isPassRiskRating");
            return (Criteria) this;
        }

        public Criteria andIsPassRiskRatingNotLike(String value) {
            addCriterion("is_pass_risk_rating not like", value, "isPassRiskRating");
            return (Criteria) this;
        }

        public Criteria andIsPassRiskRatingIn(List<String> values) {
            addCriterion("is_pass_risk_rating in", values, "isPassRiskRating");
            return (Criteria) this;
        }

        public Criteria andIsPassRiskRatingNotIn(List<String> values) {
            addCriterion("is_pass_risk_rating not in", values, "isPassRiskRating");
            return (Criteria) this;
        }

        public Criteria andIsPassRiskRatingBetween(String value1, String value2) {
            addCriterion("is_pass_risk_rating between", value1, value2, "isPassRiskRating");
            return (Criteria) this;
        }

        public Criteria andIsPassRiskRatingNotBetween(String value1, String value2) {
            addCriterion("is_pass_risk_rating not between", value1, value2, "isPassRiskRating");
            return (Criteria) this;
        }

        public Criteria andIsOfflineIsNull() {
            addCriterion("is_offline is null");
            return (Criteria) this;
        }

        public Criteria andIsOfflineIsNotNull() {
            addCriterion("is_offline is not null");
            return (Criteria) this;
        }

        public Criteria andIsOfflineEqualTo(String value) {
            addCriterion("is_offline =", value, "isOffline");
            return (Criteria) this;
        }

        public Criteria andIsOfflineNotEqualTo(String value) {
            addCriterion("is_offline <>", value, "isOffline");
            return (Criteria) this;
        }

        public Criteria andIsOfflineGreaterThan(String value) {
            addCriterion("is_offline >", value, "isOffline");
            return (Criteria) this;
        }

        public Criteria andIsOfflineGreaterThanOrEqualTo(String value) {
            addCriterion("is_offline >=", value, "isOffline");
            return (Criteria) this;
        }

        public Criteria andIsOfflineLessThan(String value) {
            addCriterion("is_offline <", value, "isOffline");
            return (Criteria) this;
        }

        public Criteria andIsOfflineLessThanOrEqualTo(String value) {
            addCriterion("is_offline <=", value, "isOffline");
            return (Criteria) this;
        }

        public Criteria andIsOfflineLike(String value) {
            addCriterion("is_offline like", value, "isOffline");
            return (Criteria) this;
        }

        public Criteria andIsOfflineNotLike(String value) {
            addCriterion("is_offline not like", value, "isOffline");
            return (Criteria) this;
        }

        public Criteria andIsOfflineIn(List<String> values) {
            addCriterion("is_offline in", values, "isOffline");
            return (Criteria) this;
        }

        public Criteria andIsOfflineNotIn(List<String> values) {
            addCriterion("is_offline not in", values, "isOffline");
            return (Criteria) this;
        }

        public Criteria andIsOfflineBetween(String value1, String value2) {
            addCriterion("is_offline between", value1, value2, "isOffline");
            return (Criteria) this;
        }

        public Criteria andIsOfflineNotBetween(String value1, String value2) {
            addCriterion("is_offline not between", value1, value2, "isOffline");
            return (Criteria) this;
        }

        public Criteria andHighestLevelIsNull() {
            addCriterion("highest_level is null");
            return (Criteria) this;
        }

        public Criteria andHighestLevelIsNotNull() {
            addCriterion("highest_level is not null");
            return (Criteria) this;
        }

        public Criteria andHighestLevelEqualTo(String value) {
            addCriterion("highest_level =", value, "highestLevel");
            return (Criteria) this;
        }

        public Criteria andHighestLevelNotEqualTo(String value) {
            addCriterion("highest_level <>", value, "highestLevel");
            return (Criteria) this;
        }

        public Criteria andHighestLevelGreaterThan(String value) {
            addCriterion("highest_level >", value, "highestLevel");
            return (Criteria) this;
        }

        public Criteria andHighestLevelGreaterThanOrEqualTo(String value) {
            addCriterion("highest_level >=", value, "highestLevel");
            return (Criteria) this;
        }

        public Criteria andHighestLevelLessThan(String value) {
            addCriterion("highest_level <", value, "highestLevel");
            return (Criteria) this;
        }

        public Criteria andHighestLevelLessThanOrEqualTo(String value) {
            addCriterion("highest_level <=", value, "highestLevel");
            return (Criteria) this;
        }

        public Criteria andHighestLevelLike(String value) {
            addCriterion("highest_level like", value, "highestLevel");
            return (Criteria) this;
        }

        public Criteria andHighestLevelNotLike(String value) {
            addCriterion("highest_level not like", value, "highestLevel");
            return (Criteria) this;
        }

        public Criteria andHighestLevelIn(List<String> values) {
            addCriterion("highest_level in", values, "highestLevel");
            return (Criteria) this;
        }

        public Criteria andHighestLevelNotIn(List<String> values) {
            addCriterion("highest_level not in", values, "highestLevel");
            return (Criteria) this;
        }

        public Criteria andHighestLevelBetween(String value1, String value2) {
            addCriterion("highest_level between", value1, value2, "highestLevel");
            return (Criteria) this;
        }

        public Criteria andHighestLevelNotBetween(String value1, String value2) {
            addCriterion("highest_level not between", value1, value2, "highestLevel");
            return (Criteria) this;
        }

        public Criteria andIsAgreeIsNull() {
            addCriterion("is_agree is null");
            return (Criteria) this;
        }

        public Criteria andIsAgreeIsNotNull() {
            addCriterion("is_agree is not null");
            return (Criteria) this;
        }

        public Criteria andIsAgreeEqualTo(String value) {
            addCriterion("is_agree =", value, "isAgree");
            return (Criteria) this;
        }

        public Criteria andIsAgreeNotEqualTo(String value) {
            addCriterion("is_agree <>", value, "isAgree");
            return (Criteria) this;
        }

        public Criteria andIsAgreeGreaterThan(String value) {
            addCriterion("is_agree >", value, "isAgree");
            return (Criteria) this;
        }

        public Criteria andIsAgreeGreaterThanOrEqualTo(String value) {
            addCriterion("is_agree >=", value, "isAgree");
            return (Criteria) this;
        }

        public Criteria andIsAgreeLessThan(String value) {
            addCriterion("is_agree <", value, "isAgree");
            return (Criteria) this;
        }

        public Criteria andIsAgreeLessThanOrEqualTo(String value) {
            addCriterion("is_agree <=", value, "isAgree");
            return (Criteria) this;
        }

        public Criteria andIsAgreeLike(String value) {
            addCriterion("is_agree like", value, "isAgree");
            return (Criteria) this;
        }

        public Criteria andIsAgreeNotLike(String value) {
            addCriterion("is_agree not like", value, "isAgree");
            return (Criteria) this;
        }

        public Criteria andIsAgreeIn(List<String> values) {
            addCriterion("is_agree in", values, "isAgree");
            return (Criteria) this;
        }

        public Criteria andIsAgreeNotIn(List<String> values) {
            addCriterion("is_agree not in", values, "isAgree");
            return (Criteria) this;
        }

        public Criteria andIsAgreeBetween(String value1, String value2) {
            addCriterion("is_agree between", value1, value2, "isAgree");
            return (Criteria) this;
        }

        public Criteria andIsAgreeNotBetween(String value1, String value2) {
            addCriterion("is_agree not between", value1, value2, "isAgree");
            return (Criteria) this;
        }

        public Criteria andAgreeTimeIsNull() {
            addCriterion("agree_time is null");
            return (Criteria) this;
        }

        public Criteria andAgreeTimeIsNotNull() {
            addCriterion("agree_time is not null");
            return (Criteria) this;
        }

        public Criteria andAgreeTimeEqualTo(Date value) {
            addCriterion("agree_time =", value, "agreeTime");
            return (Criteria) this;
        }

        public Criteria andAgreeTimeNotEqualTo(Date value) {
            addCriterion("agree_time <>", value, "agreeTime");
            return (Criteria) this;
        }

        public Criteria andAgreeTimeGreaterThan(Date value) {
            addCriterion("agree_time >", value, "agreeTime");
            return (Criteria) this;
        }

        public Criteria andAgreeTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("agree_time >=", value, "agreeTime");
            return (Criteria) this;
        }

        public Criteria andAgreeTimeLessThan(Date value) {
            addCriterion("agree_time <", value, "agreeTime");
            return (Criteria) this;
        }

        public Criteria andAgreeTimeLessThanOrEqualTo(Date value) {
            addCriterion("agree_time <=", value, "agreeTime");
            return (Criteria) this;
        }

        public Criteria andAgreeTimeIn(List<Date> values) {
            addCriterion("agree_time in", values, "agreeTime");
            return (Criteria) this;
        }

        public Criteria andAgreeTimeNotIn(List<Date> values) {
            addCriterion("agree_time not in", values, "agreeTime");
            return (Criteria) this;
        }

        public Criteria andAgreeTimeBetween(Date value1, Date value2) {
            addCriterion("agree_time between", value1, value2, "agreeTime");
            return (Criteria) this;
        }

        public Criteria andAgreeTimeNotBetween(Date value1, Date value2) {
            addCriterion("agree_time not between", value1, value2, "agreeTime");
            return (Criteria) this;
        }

        public Criteria andUserTypeIsNull() {
            addCriterion("user_type is null");
            return (Criteria) this;
        }

        public Criteria andUserTypeIsNotNull() {
            addCriterion("user_type is not null");
            return (Criteria) this;
        }

        public Criteria andUserTypeEqualTo(String value) {
            addCriterion("user_type =", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeNotEqualTo(String value) {
            addCriterion("user_type <>", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeGreaterThan(String value) {
            addCriterion("user_type >", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeGreaterThanOrEqualTo(String value) {
            addCriterion("user_type >=", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeLessThan(String value) {
            addCriterion("user_type <", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeLessThanOrEqualTo(String value) {
            addCriterion("user_type <=", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeLike(String value) {
            addCriterion("user_type like", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeNotLike(String value) {
            addCriterion("user_type not like", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeIn(List<String> values) {
            addCriterion("user_type in", values, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeNotIn(List<String> values) {
            addCriterion("user_type not in", values, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeBetween(String value1, String value2) {
            addCriterion("user_type between", value1, value2, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeNotBetween(String value1, String value2) {
            addCriterion("user_type not between", value1, value2, "userType");
            return (Criteria) this;
        }

        public Criteria andScoreMallGrantIsNull() {
            addCriterion("score_mall_grant is null");
            return (Criteria) this;
        }

        public Criteria andScoreMallGrantIsNotNull() {
            addCriterion("score_mall_grant is not null");
            return (Criteria) this;
        }

        public Criteria andScoreMallGrantEqualTo(String value) {
            addCriterion("score_mall_grant =", value, "scoreMallGrant");
            return (Criteria) this;
        }

        public Criteria andScoreMallGrantNotEqualTo(String value) {
            addCriterion("score_mall_grant <>", value, "scoreMallGrant");
            return (Criteria) this;
        }

        public Criteria andScoreMallGrantGreaterThan(String value) {
            addCriterion("score_mall_grant >", value, "scoreMallGrant");
            return (Criteria) this;
        }

        public Criteria andScoreMallGrantGreaterThanOrEqualTo(String value) {
            addCriterion("score_mall_grant >=", value, "scoreMallGrant");
            return (Criteria) this;
        }

        public Criteria andScoreMallGrantLessThan(String value) {
            addCriterion("score_mall_grant <", value, "scoreMallGrant");
            return (Criteria) this;
        }

        public Criteria andScoreMallGrantLessThanOrEqualTo(String value) {
            addCriterion("score_mall_grant <=", value, "scoreMallGrant");
            return (Criteria) this;
        }

        public Criteria andScoreMallGrantLike(String value) {
            addCriterion("score_mall_grant like", value, "scoreMallGrant");
            return (Criteria) this;
        }

        public Criteria andScoreMallGrantNotLike(String value) {
            addCriterion("score_mall_grant not like", value, "scoreMallGrant");
            return (Criteria) this;
        }

        public Criteria andScoreMallGrantIn(List<String> values) {
            addCriterion("score_mall_grant in", values, "scoreMallGrant");
            return (Criteria) this;
        }

        public Criteria andScoreMallGrantNotIn(List<String> values) {
            addCriterion("score_mall_grant not in", values, "scoreMallGrant");
            return (Criteria) this;
        }

        public Criteria andScoreMallGrantBetween(String value1, String value2) {
            addCriterion("score_mall_grant between", value1, value2, "scoreMallGrant");
            return (Criteria) this;
        }

        public Criteria andScoreMallGrantNotBetween(String value1, String value2) {
            addCriterion("score_mall_grant not between", value1, value2, "scoreMallGrant");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ucs_user
     *
     * @mbggenerated do_not_delete_during_merge Sat Dec 15 15:35:14 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ucs_user
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}