package com.wh.task.mapper;

import com.wh.task.model.User;
import com.wh.task.model.UserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ucs_user
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    int countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ucs_user
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ucs_user
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ucs_user
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ucs_user
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ucs_user
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ucs_user
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    User selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ucs_user
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ucs_user
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ucs_user
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ucs_user
     *
     * @mbggenerated Sat Dec 15 15:35:14 CST 2018
     */
    int updateByPrimaryKey(User record);
}